# Generated by Django 4.1.7 on 2023-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marehemu',
            fields=[
                ('marehemu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('jina_la_kwanza', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Shuhuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_kwanza', models.CharField(max_length=255)),
                ('jina_pili', models.CharField(max_length=255)),
                ('jina_mwisho', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('shahidi', models.CharField(max_length=255)),
                ('uhusiano', models.CharField(choices=[('Baba', 'Baba'), ('Mama', 'Mama'), ('ndugu', 'ndugu'), ('Hakuna Uhusiano', 'Hakuna Uhusiano'), ('Nyingine', 'Nyingine')], max_length=255)),
                ('simu', models.IntegerField()),
                ('Uhusiano_kipindi_kifo', models.CharField(choices=[('Ndio', 'Ndio'), ('Hapana', 'Hapana')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyForm',
        ),
    ]
