# Generated by Django 4.1.7 on 2023-05-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_marehemu_shuhuda_delete_surveyform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
