# Generated by Django 4.1.7 on 2023-05-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_delete_userprofile'),
    ]

    operations = [
    ]
