# Generated by Django 4.1.7 on 2023-05-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0005_mhanga_delete_marehemu_alter_shuhuda_uhusiano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uchunguzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mengineyo', models.TextField()),
                ('magonjwa', models.CharField(blank=True, choices=[('moyo', 'Ugonjwa wa Moyo'), ('kisukari', 'Non-fiction'), ('presha', 'Mystery'), ('saratani', 'Thriller'), ('ajali', 'Ajali'), ('pumu', 'Pumu'), ('vvu', 'VVU'), ('kifafa', 'Kifafa'), ('kifua kikuu', 'Kifua Kikuu'), ('sijui', 'Sijui')], max_length=20)),
                ('mhanga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.mhanga')),
                ('shahidi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.shuhuda')),
            ],
        ),
    ]
